---
- name: install docker
  hosts: all
  become: yes
  roles:
    - angstwad.docker_ubuntu
  tags: docker_install

- name: deploy iPerf3 server
  hosts: server
  vars:
    data_file_path: "{{ workdir }}/{{ data_file_name }}"
  tasks:
    - name: ensure the presence of workdir {{ workdir }}
      file:
        path: "{{ workdir }}"
        state: directory
    - name: delete obsolate data file
      file:
        path: "{{ data_file_path }}"
        state: absent
    - name: create data file for read by the iPerf3 server
      command: fallocate -l {{ data_file_size }} {{ data_file_path }}
    - name: start the iPerf3 server
      become: yes
      docker_container:
        cleanup: yes
        command: >
          /root/results/server_iperf3.log
          --server
          --file /root/results/{{ data_file_name }}
          --bind {{ hostvars[inventory_hostname]['ansible_' + server_outbound_interface]['ipv4']['address'] }}
        detach: yes
        force_kill: yes
        image: ljishen/iperf3
        name: iperf3
        network_mode: host
        pull: yes
        recreate: yes
        state: started
        volumes:
          - "{{ workdir }}:/root/results"
