---
# This is the only correct way to implement retries of a list of tasks
# Related issues:
#   https://github.com/ansible/ansible/issues/17098 (Loop-until does not loop over includes)
#   https://github.com/ansible/ansible/issues/16621 (Feature request: until for blocks)

- name: (servers {{ num_servs }}/{{ total_servs }}, round {{ index }}/{{ repetition }}, size {{ bytes }}) setup retries
  include_tasks: single_test.yml
  with_sequence: count=3
  loop_control:
    loop_var: cur_retry

- set_fact: exe_continue=yes
