---
- name: (servers {{ num_servs }}/{{ total_servs }}, round {{ index }}/{{ repetition }}, size {{ bytes }}) run the server
  become: yes
  docker_container:
    capabilities: SYS_ADMIN
    command: >
      stat
      /root/pyben-nio/src/run
      --server start
      --bind {{ hostvars[groups['servers'][serv_idx | int]]['ansible_' + server_outbound_interface]['ipv4']['address'] }}
      --size {{ lookup('template', 'templates/allocator.j2').split(',')[serv_idx | int] }}
      --port {{ port }}
      --filename /root/{{ server_data_filename }}
      --bufsize {{ bufsize }}
    cpuset_cpus: "{{ perf_server_container_cpuset }}"
    detach: no
    force_kill: yes
    image: "{{ perf_image_name }}"
    name: "{{ perf_server_container_name }}"
    network_mode: host
    pull: no
    recreate: yes
    state: started
    volumes:
      - "{{ workdir }}/{{ server_data_filename }}:/root/{{ server_data_filename }}:ro"
      - "{{ workdir }}/pyben-nio:/root/pyben-nio:ro"
  delegate_to: "{{ hostvars[groups['servers'][serv_idx | int]]['inventory_hostname'] }}"
  async: "{{ 60 * 60 }}"  # each task last for at most 1 hour
  poll: 0
  with_sequence: start=0 count={{ num_servs }}
  loop_control:
    loop_var: serv_idx
  register: perf_server_async_results

- name: wait for 2 seconds to ensure {{ num_servs }} servers have set up
  pause:
    seconds: 2

- name: (servers {{ num_servs }}/{{ total_servs }}, round {{ index }}/{{ repetition }}, size {{ bytes }}) run the client
  become: yes
  docker_container:
    capabilities: SYS_ADMIN
    command: >
      stat
      /root/pyben-nio/src/run
      --client start
      --addresses
        {%- for i in range(num_servs | int) %} {{ hostvars[groups['servers'][i]]['ansible_' + server_outbound_interface]['ipv4']['address'] }} {% endfor -%}
      --size {{ bytes }}
      --port {{ port }}
      --bind {{ hostvars[groups['client'][0]]['ansible_' + client_incoming_interface]['ipv4']['address'] }}
      --bufsize {{ bufsize }}
    cpuset_cpus:
      "{{ perf_client_container_cpuset_start }}-{{ perf_client_container_cpuset_end if perf_client_container_cpuset_end is number else perf_client_container_cpuset_start + num_servs | int - 1 }}"
    detach: no
    force_kill: yes
    image: "{{ perf_image_name }}"
    name: "{{ perf_client_container_name }}"
    network_mode: host
    pull: no
    recreate: yes
    state: started
    volumes:
      - "{{ workdir }}/pyben-nio:/root/pyben-nio:ro"
  delegate_to: "{{ hostvars[groups['client'][0]]['inventory_hostname'] }}"
  register: perf_client_result

- name: (servers {{ num_servs }}/{{ total_servs }}, round {{ index }}/{{ repetition }}, size {{ bytes }}) collect server outputs
  # need to activate privilege escalation to set the user to root to be able to access the job file under /root/.ansible_async/
  become: yes
  async_status:
    jid: "{{ result_item.ansible_job_id }}"
  delegate_to: "{{ result_item._ansible_delegated_vars.ansible_delegated_host }}"
  loop: "{{ perf_server_async_results.results }}"
  loop_control:
    loop_var: "result_item"
  register: perf_server_async_poll_outputs

- name: (servers {{ num_servs }}/{{ total_servs }}, round {{ index }}/{{ repetition }}, size {{ bytes }}) save server outputs
  copy:
    backup: yes
    content: "{{ output_item.ansible_facts.docker_container.Output }}"
    dest: "{{ output_dir }}/logs/perf_server_{{ bytes }}_{{ index }}_{{ num_servs }}servs_{{ output_item.result_item.serv_idx }}.log"
    force: yes
  loop: "{{ perf_server_async_poll_outputs.results }}"
  loop_control:
    loop_var: "output_item"
  no_log: yes

- name: (servers {{ num_servs }}/{{ total_servs }}, round {{ index }}/{{ repetition }}, size {{ bytes }}) save client output
  copy:
    backup: yes
    content: "{{ perf_client_result.ansible_facts.docker_container.Output }}"
    dest: "{{ output_dir }}/logs/perf_client_{{ bytes }}_{{ index }}_{{ num_servs }}servs.log"
    force: yes

- name: (servers {{ num_servs }}/{{ total_servs }}, round {{ index }}/{{ repetition }}, size {{ bytes }}) extract data
  command: >
    scripts/extract2csv.sh
    {{ output_dir }}/logs/perf_client_{{ bytes }}_{{ index }}_{{ num_servs }}servs.log
    {{ output_dir }}/{{ result_file_prefix }}.csv
    {{ bytes }},{{ num_servs }}

- name: drop file cache
  become: yes
  # See https://www.kernel.org/doc/Documentation/sysctl/vm.txt
  shell: sync && echo 3 > /proc/sys/vm/drop_caches
  delegate_to: "{{ hostvars[groups['servers'][serv_idx | int]]['inventory_hostname'] }}"
  with_sequence: start=0 count={{ num_servs }}
  loop_control:
    loop_var: serv_idx
