---
- name: (index {{ index }}/{{ repetition }}, size {{ bytes }}) start tests for variable number of servers
  include_tasks: retries.yml
  vars:
    total_servs: "{{ groups['servers'] | length }}"
  with_sequence: count={{ total_servs }}
  loop_control:
    loop_var: num_servs
