---
- name: ensure common prerequisites
  hosts: all
  any_errors_fatal: true
  roles:
    - { role: ../common/roles/prerequisites, become: yes }
  tasks:
    - name: install/update Pyben-nio
      git:
        clone: yes
        depth: 1
        dest: "{{ workdir }}/pyben-nio"
        force: yes
        recursive: no
        repo: https://github.com/ljishen/pyben-nio.git
        update: yes
        version: HEAD
      async: 30
      # we poll the result so that we know it fails if we didn't have write permission on {{ workdir }}
      poll: 1
    - name: install perf and iostat
      become: yes
      apt:
        install_recommends: no
        name:
          - linux-tools-common
          - linux-tools-{{ ansible_kernel }}
          - sysstat
        state: latest
        cache_valid_time: "{{ 24 * 60 * 60 }}"  # cache valid for one day
      async: "{{ 2 * 60 }}"
      poll: 1

- hosts: servers
  any_errors_fatal: true
  vars:
    data_file_path: "{{ workdir }}/{{ server_data_filename }}"
  tasks:
    - name: delete obsolate data file
      file:
        path: "{{ data_file_path }}"
        state: absent
      when: force_create_data_file
    - name: create {{ server_data_file_size }} data file for read by the server
      command: >
        {{ workdir }}/pyben-nio/src/tools.py {{ server_data_file_size }}
        --filename {{ workdir }}/{{ server_data_filename }}
      args:
        creates: "{{ workdir }}/{{ server_data_filename }}"
      async: "{{ 10 * 60 * 60 }}"
      poll: 30

- name: config CPU isolation from the kernel scheduler
  hosts: all
  vars:
    nr_cpus: '3'
    isolcpus: '1,2'
  any_errors_fatal: true
  tasks:
    - name: fetch current kernel boot parameters
      setup:
        filter: ansible_cmdline
    - name: check kernel boot parameters
      set_fact:
        boot_params_invalid: >
          {{ 'nr_cpus' not in ansible_cmdline or ansible_cmdline.nr_cpus != nr_cpus or 'isolcpus' not in ansible_cmdline or ansible_cmdline.isolcpus != isolcpus }}
    - name: check number of vCPUs
      command: nproc
      register: cmd_nproc
      when: boot_params_invalid
    - debug: msg="The system has only {{ cmd_nproc.stdout }} (< {{ nr_cpus }}) virtual processors"
      when: not force_update_kernel_boot_parameters and boot_params_invalid and cmd_nproc.stdout is defined and cmd_nproc.stdout | int < nr_cpus | int
      failed_when: true
    - name: remove old kernel boot parameters
      become: yes
      command: >
        sed -i 's/ *nr_cpus=[^ "]*\| *isolcpus=[^ "]*//g' /etc/default/grub
      args:
        warn: no
      when: boot_params_invalid
    - name: append kernel boot parameters
      become: yes
      lineinfile:
        backrefs: yes
        line: '\1 nr_cpus={{ nr_cpus }} isolcpus={{ isolcpus }}"'
        path: /etc/default/grub
        regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT="[^"]*)'
        state: present
      when: boot_params_invalid
    - name: update grub2 config file
      become: yes
      command: update-grub
      async: 10
      poll: 2
      when: boot_params_invalid

- name: reboot if boot parameters updated
  hosts:
    - servers
    - client
  become: yes
  tasks:
    - command: reboot
      when: boot_params_invalid

- name: config CPUs for IRQ handling
  hosts: all
  any_errors_fatal: true
  become: yes
  tasks:
    - name: config SMP IRQ affinity for network interrupts
      script: >
        scripts/net_smp_affinity {{ net_dev_in_count }} {{ net_dev_in_count_cpu_mask }}
        &&
        scripts/net_smp_affinity {{ net_dev_out_of_count }} {{ net_dev_out_of_count_cpu_mask }}
      register: cmd_net_smp_affinity
    - debug: msg={{ cmd_net_smp_affinity.stdout_lines }}
    - name: stop irqbalance service
      service:
        name: irqbalance
        state: stopped

- hosts: all
  vars:
    iostat_log_file: "{{ workdir }}/{{ iostat_log_filename }}.{{ inventory_hostname }}"
    iostat_pid_file: "{{ workdir }}/{{ iostat_pid_filename }}"
  tasks:
    - name: backup {{ iostat_log_file }}
      copy:
        backup: yes
        content: ""
        dest: "{{ iostat_log_file }}"
        force: yes
    - name: stop iostat daemon if necessary
      shell: kill $(cat {{ iostat_pid_file }}) ; rm {{ iostat_pid_file }}
      args:
        removes: "{{ iostat_pid_file }}"
    - name: run iostat as daemon
      # we use stdbuf to turn off the buffering of the output redirection.
      #   https://linux.die.net/man/1/stdbuf
      #   https://stackoverflow.com/a/1429973
      shell: >
        stdbuf -oL -eL iostat -t 1 > {{ iostat_log_file }} 2>&1 & echo $! > {{ iostat_pid_file }}

- name: run bench
  hosts: localhost
  vars:
    output_dir: "{{ playbook_dir }}/output"
    logs_dir: "{{ output_dir }}/logs"
  tasks:
    - include_tasks: ../common/tasks/run_bench.yml

- hosts: all
  vars:
    iostat_logs_dir: "{{ playbook_dir }}/output/logs/iostat/"
    iostat_pid_file: "{{ workdir }}/{{ iostat_pid_filename }}"
  tasks:
    - name: ensure the presence of {{ iostat_logs_dir }}
      file:
        path: "{{ iostat_logs_dir }}"
        state: directory
    - name: stop iostat daemon
      shell: kill $(cat {{ iostat_pid_file }}) ; rm {{ iostat_pid_file }}
      args:
        removes: "{{ iostat_pid_file }}"
    - name: collect iostat logs
      fetch:
        dest: "{{ iostat_logs_dir }}"
        fail_on_missing: yes
        flat: yes
        src: "{{ workdir }}/{{ iostat_log_filename }}.{{ inventory_hostname }}"
