---
- name: ensure all prerequisites
  hosts: all
  roles:
    - { role: angstwad.docker_ubuntu, become: yes, tags: 'install_docker' }
  tasks:
    - name: load common variables
      include_vars: group_vars/all
    - name: ensure the presence of workdir {{ workdir }}
      file:
        path: "{{ workdir }}"
        state: directory
