---
- set_fact:
  # This variable is used to control whether to repeat/skip a single test or not.
    exe_continue: yes

- name: start tests for transmission size {{ bytes }}
  include_tasks: "{{ playbook_dir }}/include/test.yml"
  with_sequence: count={{ repetition }}
  loop_control:
    loop_var: index
