---
- name: ensure the presence of {{ logs_dir }}
  file:
    path: "{{ logs_dir }}"
    state: directory
- name: create the result file
  # Use the copy module to backup the old file if necessary
  copy:
    backup: "{{ backup_results }}"
    content: ""
    dest: "{{ output_dir }}/{{ result_filename }}"
    force: "{{ backup_results }}"
- include_tasks: repetition.yml
  loop: "{{ transmission_sizes }}"
  loop_control:
    loop_var: bytes
    index_var: sizes_idx
