---
- import_playbook: ../common/prerequisites.yml

- name: install fio to receiver
  hosts: receiver
  any_errors_fatal: true
  tasks:
    - name: install the libaio development package
      # Missing this package will cause the following error message:
      # error while loading shared libraries:
      #   libaio.so.1: cannot open shared object file: No such file or director
      become: yes
      apt:
        install_recommends: no
        # This package has the same name in Ubuntu and Debian
        name: libaio1
        state: latest
        update_cache: yes
    - name: delete obsolate installation dir
      shell: rm -rf {{ workdir }}/{{ fio_dir_prefix }}*
      args:
        warn: no
    - name: download fio-{{ receiver_fio_version }}
      unarchive:
        dest: "{{ workdir }}"
        remote_src: yes
        src: https://codeload.github.com/axboe/fio/tar.gz/fio-{{ receiver_fio_version }}
    - name: configure and make fio-{{ receiver_fio_version }}
      shell: ./configure && make -j "$(nproc)"
      args:
        chdir: "{{ workdir }}/{{ fio_dir_prefix }}{{ receiver_fio_version }}"

- hosts: sender
  tasks:
    - name: deploy the jobfile for sender
      template:
        dest: "{{ workdir }}/sender.fio"
        force: yes
        src: templates/netio_sender.j2

- hosts: receiver
  tasks:
    - name: deploy the jobfile for receiver
      template:
        dest: "{{ workdir }}/receiver.fio"
        force: yes
        src: templates/netio_receiver.j2

- name: run bench
  hosts: localhost
  vars:
    output_dir: "{{ playbook_dir }}/output"
  tasks:
    - include_tasks: ../common/tasks/run_bench.yml
